### ISSUE TITLE
BCMorganizer.exe bug

### ISSUE THREAD

**Issue by Illua110** [KyonkoYuuki/YaBCMOrganizer#1]
Hello God, excuse me, there seems to be some problems with your latest version of bcmorganizer.exe. When I import BCM files with tools, there will be bugs when I save new BCM files into the game. The specific problem is that the keys are gray, the action of BCM keys is invalid, and then I use XML tools to transform into. bcm.xml text. When the program opens, all the code is scrambled. What's the reason? Tip: The old version you released can be used normally and there are no bugs, but the new version has the bugs mentioned above. I hope you can fix them. Thank you very much!!!

**Comment by XtroGamez** [comment]
It isn't going good with my Anti-Virus. So I need you to fix it please.
