### ISSUE TITLE
YaBCMOrganizer : unintutive behavior

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBCMOrganizer#2]
in YaBCMOrganizer, by pressing **CTRL + C** to copy a certain value (ie: Ki Cost), the tool instead copies the entire BCM entry that is being worked on.

its a bit awkward, since its not something you expect CTRL + C to do, it is universally meant to copy certain values or text.

instead of removing such behavior, maybe have an option for it in a Settings menu (checkbox).
ie : "Set CTRL + C & CTRL + V to copy/paste entries"

**Comment by KyonkoYuuki** [comment]
Turns out wx actually parses menu text and if it finds shortcuts, creates them automatically.  I just removed all those menu items from the main edit menu, as that was the global shortcuts overriding everything.
