### ISSUE TITLE
Floating and Standing Activators are swapped

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBCMOrganizer#4]
![image](https://user-images.githubusercontent.com/47185022/82841013-4ae98380-9edd-11ea-9b21-7b0267b69233.png)

YaBCM seems to have these 2 names swapped, Floating conditions are Standing conditions in-game and vice versa.

**Comment by KyonkoYuuki** [comment]
So are you saying this is wrong? (From the moveset manual)
![image](https://user-images.githubusercontent.com/51934173/82847638-3b5a4280-9ebd-11ea-89bc-aabbae70045e.png)

**Comment by UnleashedGH** [comment]
> So are you saying this is wrong? (From the moveset manual)
> ![image](https://user-images.githubusercontent.com/51934173/82847638-3b5a4280-9ebd-11ea-89bc-aabbae70045e.png)

indeed. will fix that in the manual.

**Comment by KyonkoYuuki** [comment]
noted and done
