### ISSUE TITLE
YaBCM v0.2.0 : corrupted BCM files after saving

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBCMOrganizer#8]
YaBCM v.0.2.0 corrupts BCM files by reading and saving entries incorrectly 
will be using **167_VGT_GLX_PLAYER.bcm**

first, it seems that YaBCM reads a "Sibinling_GoTo_Idx" for entry 2, even though that's not the case when converting the file to xml using genser/xv2 serializer
![image](https://user-images.githubusercontent.com/47185022/83361998-91842580-a396-11ea-8ea7-34c42ac0d8d9.png)

next we save the BCM, and the result is :
![image](https://user-images.githubusercontent.com/47185022/83362014-a3fe5f00-a396-11ea-8ae1-b067ba423ef4.png)

YaBCM deletes entry 4, and sets a Sibinling_GoTo_Idx for entry 1

now we save and reopen again :
![image](https://user-images.githubusercontent.com/47185022/83362025-bb3d4c80-a396-11ea-94cc-b239662ff18a.png)

YaBCM deletes entry 3

repeating this will result in all the BCM entries getting deleted, include Root (entry 0) until the BCM gives an "index out of range" when opening as it has 0 entries

**Random Behaviors**
sometimes, say Entry X has a Child Y, YaBCM deletes Child Y and then sets a "Child_GoTo_Idx" to Entry X which gets set to equal Y , even though child Y no longer exists

though i can't always replicate said issue

**Comment by KyonkoYuuki** [comment]
AKA what happens when you forget to save the Entry 0

**Comment by KyonkoYuuki** [comment]
```
first, it seems that YaBCM reads a "Sibinling_GoTo_Idx" for entry 2, even though that's not the case when converting the file to xml using genser/xv2 serializer
```

The serializer omits the sibling idx if it matches its actual sibling in the xml file (hence why the tree view sometimes and sometimes doesn't show it).  The value you see in the BCM organizer is the same as what gets read/written.
