### ISSUE TITLE
YaBCM v0.2.0 : Copying complex entries takes too long

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBCMOrganizer#9]
in GOK_PLAYER.bcm, if i wanted to copy entry 147, the program takes 8 to 15 minutes before the copy process is complete.
![image](https://user-images.githubusercontent.com/47185022/83362334-14a67b00-a399-11ea-824e-cd7bf00122d0.png)

**Comment by KyonkoYuuki** [comment]
improved performance
